version: '3.8'

services:
  qdrant_db:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    ports:
      - "6333:6333" # API 포트
      - "6334:6334" # 웹 UI 포트
    volumes:
      - ./qdrant_data:/qdrant/storage
    restart: always